/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
 *
 * Generated on: 26-Jun-2013 09:47:25
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s29,30 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

#ifndef FDACOEFS_H
#define FDACOEFS_H

const int BL = 64;
const short B[64] = {
        0,      0,      0,      1,      0,     -2,     -5,     -8,     -9,
       -4,      7,     22,     34,     35,     22,     -1,    -19,    -17,
        8,     37,     30,    -58,   -239,   -463,   -608,   -502,      9,
      987,   2343,   3830,   5108,   5847,   5847,   5108,   3830,   2343,
      987,      9,   -502,   -608,   -463,   -239,    -58,     30,     37,
        8,    -17,    -19,     -1,     22,     35,     34,     22,      7,
       -4,     -9,     -8,     -5,     -2,      0,      1,      0,      0,
        0
};

#endif
